/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Paricutin(props) {
  const { nodes, materials } = useGLTF('./models/paricutin.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paricutin.geometry}
        material={materials.Paricutin}
        material-envMapIntensity={1.2}
        rotation={[0, 0, 0]}
        scale={0.04}
      />
    </group>
  )
}

useGLTF.preload('./models/paricutin.glb')
