/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Paricutin(props) {
    const { nodes, materials } = useGLTF('./models/paricutin.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Remesh.geometry}
                material={materials.Paricutin}
                material-envMapIntensity = {1.2}
                material-roughness = {1}
                material-metalness = {0.0}
            />
        </group>
    )
}

useGLTF.preload('./models/paricutin.glb')
