/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Placeholder(props) {
  const { nodes, materials } = useGLTF('./models/ParicutinPlaceHolder.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paricutin001.geometry}
        material={materials.PlaceHolder}
        rotation={[0, 0, 0]}
        scale={0.04}
      />
    </group>
  )
}

useGLTF.preload('./models/ParicutinPlaceHolder.glb')
